baseURL = "https://blog.ceto.xyz"
CanonifyUrl = true
languageCode = "en-us"
title = "Ceto"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "hugo-notepadium"

[params]
  description = "Erik Goodman's blog on technology, tech-adjacent things, etc."