baseURL = "https://blog.ceto.xyz"
CanonifyUrl = true
languageCode = "en-us"
title = "Ceto"
theme = "hugo-notepadium"
enableRobotsTXT = true
copyright = "©2020 Erik Goodman"

[markup.highlight]
codeFences = true
noClasses = false

[params]
  description = "Erik Goodman's blog on technology, tech-adjacent things, etc."
	style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
	dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"
	logo = ""  # if you have a logo png
	license = ""  # CC License

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "dracula"
darkTheme = "xcode-dark"  # apply this theme in dark mode

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/

